# Generated by Django 3.0.6 on 2020-05-27 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200526_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='auth_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
