# Generated by Django 3.0.6 on 2020-05-27 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_auth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='abt_auth',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
