# Generated by Django 3.0.6 on 2020-05-28 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200528_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='content3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
